######################################################################
#
# File name : toplevel_tb_wave.do
# Created on: Tue Aug 15 05:57:06 +0100 2023
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
