######################################################################
#
# File name : toplevel_tb_compile.do
# Created on: Tue Aug 15 20:42:38 +0100 2023
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/work
E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/msim

E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/msim/xil_defaultlib

E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlog  -incr -mfcu -work xil_defaultlib  \
"toplevel_tb_time_synth.v" \

E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlog  -incr -mfcu -sv -work xil_defaultlib  \
"../../../../../vector_database.srcs/sources_1/new/uart.sv" \
"../../../../../vector_database.srcs/sources_1/new/uart_rx.sv" \
"../../../../../vector_database.srcs/sources_1/new/uart_tx.sv" \
"../../../../../vector_database.srcs/sim_1/new/toplevel_tb.sv" \

quit -force

