######################################################################
#
# File name : fifo_tb_simulate.do
# Created on: Sun Aug 20 16:37:08 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.fifo_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {fifo_tb_wave.do}

view wave
view structure
view signals

do {fifo_tb.udo}

run 1000ns
