######################################################################
#
# File name : fifo_tb_wave.do
# Created on: Sun Aug 20 04:48:33 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
