######################################################################
#
# File name : Instruction_mem_tb_wave.do
# Created on: Sat Aug 19 23:45:53 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
