######################################################################
#
# File name : Ram_tb_wave.do
# Created on: Sun Aug 20 02:19:55 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
