######################################################################
#
# File name : toplevel_tb_compile.do
# Created on: Wed Aug 23 01:25:07 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/work
E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/msim

E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/msim/xil_defaultlib

E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlog  -incr -mfcu -sv -work xil_defaultlib  \
"../../../../vector_database.srcs/sources_1/new/alu.sv" \
"../../../../vector_database.srcs/sources_1/new/cpu.sv" \
"../../../../vector_database.srcs/sources_1/new/fifo_interface.sv" \
"../../../../vector_database.srcs/sources_1/new/fifo_out.sv" \
"../../../../vector_database.srcs/sources_1/new/long_stack.sv" \
"../../../../vector_database.srcs/sources_1/new/ram.sv" \
"../../../../vector_database.srcs/sources_1/new/rom.sv" \
"../../../../vector_database.srcs/sources_1/new/toplevel.sv" \
"../../../../vector_database.srcs/sources_1/new/uart.sv" \
"../../../../vector_database.srcs/sources_1/new/uart_rx.sv" \
"../../../../vector_database.srcs/sources_1/new/uart_tx.sv" \
"../../../../vector_database.srcs/sim_1/new/toplevel_tb.sv" \


# compile glbl module
E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlog -work xil_defaultlib "glbl.v"

quit -force

