######################################################################
#
# File name : toplevel_tb_simulate.do
# Created on: Wed Aug 23 01:25:11 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.toplevel_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {toplevel_tb_wave.do}

view wave
view structure
view signals

do {toplevel_tb.udo}

run 1000ns
