######################################################################
#
# File name : toplevel_tb_wave.do
# Created on: Wed Aug 09 17:57:31 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
