######################################################################
#
# File name : uart_rx_tb_wave.do
# Created on: Sat Aug 19 05:25:46 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
