######################################################################
#
# File name : uart_tx_tb_simulate.do
# Created on: Sat Aug 19 04:20:40 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.uart_tx_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {uart_tx_tb_wave.do}

view wave
view structure
view signals

do {uart_tx_tb.udo}

run 1000ns
