######################################################################
#
# File name : uart_tx_tb_compile.do
# Created on: Sat Aug 19 04:20:39 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/work
E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/msim

E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlib modelsim_lib/msim/xil_defaultlib

E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlog  -incr -mfcu -sv -work xil_defaultlib  \
"../../../../vector_database.srcs/sources_1/new/uart_tx.sv" \
"../../../../vector_database.srcs/sim_1/new/uart_tx_tb.sv" \


# compile glbl module
E:\\IntelFPGA\\18.1\\modelsim_ase\\win32aloem\\vlog -work xil_defaultlib "glbl.v"

quit -force

