######################################################################
#
# File name : uart_rx_tb_simulate.do
# Created on: Sat Aug 19 17:05:10 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.uart_rx_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {uart_rx_tb_wave.do}

view wave
view structure
view signals

do {uart_rx_tb.udo}

run 1000ns
