######################################################################
#
# File name : uart_tx_tb.udo
# Created on: Sat Aug 19 03:37:58 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
