######################################################################
#
# File name : uart_rx_tb.udo
# Created on: Sat Aug 19 05:25:46 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
