######################################################################
#
# File name : uart_tx_tb_wave.do
# Created on: Sat Aug 19 03:37:58 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
